### ISSUE TITLE
[1.10.2 - 1.2.0] Upon reloading world, all dispatchers facing downwards

### ISSUE THREAD

**Issue by ghost** [KidsDontPlay/Transprot#3]
Fairly self-explanatory title; after putting dispatchers onto anything, leaving the world, and rejoining it, all dispatchers that weren't already facing (towards the inventory they're pulling from) downwards are now doing so.

Perhaps also worth noting that the now downwards facing dispatchers will no longer connect to the inventory they were originally facing, but will correctly use any inventory they are facing towards after the world reload.

**Comment by KidsDontPlay** [comment]
pls use the latest version
