### ISSUE TITLE
[1.10.2 - 1.4.0] Unable to crouch right click anything with linker

### ISSUE THREAD

**Issue by ghost** [KidsDontPlay/Transprot#4]
Like the title says, in 1.4.0 I'm unable to link dispatchers to anything as the linking tool doesn't do anything upon crouch right clicking a dispatcher or an inventory.

**Comment by KidsDontPlay** [comment]
that's weird.
do you have the latest limelib version?
does it work with only transprot installed?
does the log have any errors?

**Comment by chickenblue** [comment]
Have the same problem with version 1.10.2. Have it tried without other mods, no success. Different versions of "limelib" all without success. Something is wrong.

**Comment by KidsDontPlay** [comment]
do you play in multiplayer?

**Comment by chickenblue** [comment]
I have tried it on my own server as well as in the singleplayer. Now I use the stable version 1.2.0. But even with this I have to re-place the "Dispatcher" every time I re-enter the server so it works again.

**Comment by KidsDontPlay** [comment]
I figured out where the problem is. But I currently don't know why it happens.
